version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: optishiftdb
    restart: always
    environment:
      POSTGRES_DB: optishiftdb
      POSTGRES_USER: optishift
      POSTGRES_PASSWORD: optishift123
    ports:
      - "5432:5432"